#!/bin/bash

source "../common.sh"

datasets=(
#	"2500-2rp-ob-1-20-0.05"
	"2500-2rp-ob-2-10-0.05"
#	"2500-2rp-ob-3-5-0.05"
)

b_degrees=(
	"1"
)

t_maxs=(
	"0.005"
)

#----------------------------------------------------------------------------------------------------

#make -C .. "do_fit" || exit 1

for dataset in ${datasets[*]}
do
	for b_degree in ${b_degrees[*]}
	do
		for t_max in ${t_maxs[*]}
		do
			dir="fits/$dataset/exp$b_degree,t_max=$t_max"
			mkdir -p "$dir"

			echo "* $dir"

			extra_config=""

			if [ $t_max == "0.005" ]
			then
				extra_config="-t-tr1 0.010 -t-tr2 0.011"
			fi

			Ap="0"
			if [ "${t_max},${b_degree}" == "0.005,1" ]; then Ap="643.3"; fi
			if [ "${t_max},${b_degree}" == "0.005,2" ]; then Ap="646.2"; fi
			if [ "${t_max},${b_degree}" == "0.005,3" ]; then Ap="644.4"; fi

			../do_fit -input "$dataset" -b-degree "$b_degree" -t-max "$t_max" $extra_config\
					-use-stat-unc 1 -use-syst-unc 1 -use-norm-unc 0\
					-reweight-low-t-points 1\
					-use-b1-fixed 1 -b1-value 10.35\
					-use-normalisation-from-a 1 -Ap-value "$Ap"\
					-output "$dir/fit.root" -results "$dir/fit.out" \
				&> "$dir/fit.log" &
		done
	done
done
