#!/bin/bash

base_dir="/afs/cern.ch/work/j/jkaspar/analyses/elastic/6500GeV/combined/coulomb_analysis_1"

#----------------------------------------------------------------------------------------------------

dir="approach2_step_b"
mkdir -p "$dir"

$base_dir/do_fit\
		-input "simu-ob-2-10-0.05" -b-degree "1" -t-min "0" -t-max "0.0015" -t-tr1 "0.015" -t-tr2 "0.019" \
		-use-stat-unc 1 -use-syst-unc 1 -use-norm-unc 0\
		-reweight-low-t-points 0\
		-use-b1-fixed 1 -b1-value 10.35\
		-use-normalisation-fit-parameter 1 -use-normalisation-chisq-term 1 -use-normalisation-limit 0\
		-output "$dir/fit.root" -results "$dir/fit.out" -tex "$dir/fit.tex" \
	&> "$dir/fit.log"

eta=`cat $dir/fit.log|grep "eta-->"`
eta=${eta#*-->}

#----------------------------------------------------------------------------------------------------

dir="approach2_step_c"
mkdir -p "$dir"

$base_dir/do_fit\
		-input "simu-ob-2-10-0.05" -b-degree "1" -t-min "0" -t-max "0.07" -t-tr1 "0.09" -t-tr2 "0.25" \
		-use-stat-unc 1 -use-syst-unc 1 -use-norm-unc 0\
		-use-b1-fixed 1 -b1-value 10.35 \
		-use-normalisation-fit-parameter 1 -use-normalisation-chisq-term 0 \
		-use-eta-fixed 1 -eta-value "$eta" \
		-output "$dir/fit.root" -results "$dir/fit.out" -tex "$dir/fit.tex" \
	&> "$dir/fit.log"
