#!/bin/bash


fitter="/afs/cern.ch/work/j/jkaspar/analyses/elastic/6500GeV/combined/coulomb_analysis_1/do_fit"

#----------------------------------------------------------------------------------------------------

make -C .. "do_fit" || exit 1

#----------------------------------------------------------------------------------------------------

function RunOne()
{
	local simu_dir="$dir_base/$model/$unc/norm$norm/$binning/seed$seed"

	local t

	local ae_stat="0"
	local ae_syst="0"

	local norm_sigma="0.00"

	t=`echo "$unc"|grep "stat"`
	if [ -n "$t" ]; then ae_stat="1"; fi

	t=`echo "$unc"|grep "syst"`
	if [ -n "$t" ]; then ae_syst="1"; fi

	# this is also exceptional behaviour
	if [ "$unc" == "norm" ]; then ae_stat="1"; ae_syst="1"; fi

	# this is an exceptional behaviour for the study of normalisation impact
	if [ "$unc" == "none" ]; then ae_stat="1"; ae_syst="1"; fi

	echo "* $simu_dir"
	cd "$simu_dir"

	nB="${model%,*}"
	nB="${nB#exp}"

	# loop over ranges
	for t_max in ${fitRanges[@]}
	do
		local fit_dir="exp$nB,$unc,$t_max"
		echo "  $fit_dir"
		mkdir -p "$fit_dir"

		local extra_config=""

		if [ $t_max == "0.07" ]
		then
			extra_config="-t-tr1 0.05 -t-tr2 0.12"
		fi

		if [ $t_max == "0.15" ]
		then
			extra_config="-t-tr1 0.12 -t-tr2 0.22"
		fi

		# TODO: normalistaion uncertainty
		"$fitter" \
			-input "simu-$binning" -b-degree "$nB" -t-max "$t_max" $extra_config \
			-use-stat-unc "$ae_stat" -use-syst-unc "$ae_syst" \
			-output "$fit_dir/fit.root" -results "$fit_dir/fit.out" \
				&> "$fit_dir/fit.log"
	done

	cd - &> /dev/null
}

#----------------------------------------------------------------------------------------------------

function RunOneSet()
{
	for seed in `seq 1 $max_seed`
	do
		RunOne
	done
}

#----------------------------------------------------------------------------------------------------

function RunMultiple()
{
	for model in ${models[@]}
	do
		for unc in ${uncertainties[@]}
		do
			for norm in ${norms[@]}
			do
				for binning in ${binnings[@]}
				do
					RunOneSet &
				done
			done
		done
	done
}

#----------------------------------------------------------------------------------------------------
# fit study
#----------------------------------------------------------------------------------------------------

dir_base="simu-fit-study"

models=(
	"exp1,rho=0.10"
	"exp1,rho=0.14"
	"exp2,rho=0.10"
	"exp2,rho=0.14"
	"exp3,rho=0.10"
	"exp3,rho=0.14"
)

uncertainties=(
	"stat"
	"stat+syst"
	"stat+syst+norm"
	"norm"
)

norms=(
	"0.00"
)

binnings=(
	"ob-3-5-0.05"
)

max_seed="100"

fitRanges=(
	"0.07"
	"0.15"
)

RunMultiple



#----------------------------------------------------------------------------------------------------
# fit-bias study as function of normalisation error
#----------------------------------------------------------------------------------------------------

dir_base="simu-norm-study"

models=(
	"exp1,rho=0.06"
	"exp1,rho=0.10"
	"exp1,rho=0.14"
	"exp3,rho=0.06"
	"exp3,rho=0.10"
	"exp3,rho=0.14"
)

uncertainties=(
	"none"
)

norms=(
	"+0.10"
	"+0.08"
	"+0.06"
	"+0.04"
	"+0.02"
	"0.00"
	"-0.02"
	"-0.04"
	"-0.06"
	"-0.08"
	"-0.10"
)

binnings=(
	"ob-2-10-0.05"
)

max_seed="1"

#RunMultiple
