#!/bin/bash

source "../common.sh"

datasets=(
#	"2500-2rp-ob-1-20-0.05"
	"2500-2rp-ob-2-10-0.05"
#	"2500-2rp-ob-3-5-0.05"
)

b_degrees=(
	"1"
	"2"
	"3"
)

t_maxs=(
	"0.07"
#	"0.13"
	"0.15"
#	"0.17"
)

#----------------------------------------------------------------------------------------------------

#make -C .. "do_fit" || exit 1

for dataset in ${datasets[*]}
do
	for b_degree in ${b_degrees[*]}
	do
		for t_max in ${t_maxs[*]}
		do
			dir="fits/$dataset/exp$b_degree,t_max=$t_max"
			mkdir -p "$dir"

			echo "* $dir"

			extra_config=""
			SetStandardExtraConfig

			../do_fit -input "$dataset" -b-degree "$b_degree" -t-max "$t_max" $extra_config\
					-use-stat-unc 1 -use-syst-unc 1 -use-norm-unc 0\
					-reweight-low-t-points 1\
					-use-normalisation-fit-parameter 1 -use-normalisation-chisq-term 0 -use-normalisation-limit 0\
					-output "$dir/fit.root" -results "$dir/fit.out" \
				&> "$dir/fit.log" &
		done
	done
done
