#!/bin/bash

source "../common.sh"

datasets=(
#	"2500-2rp-ob-1-20-0.05"
	"2500-2rp-ob-2-10-0.05"
#	"2500-2rp-ob-3-5-0.05"
)

b_degrees=(
	"1"
	"2"
	"3"
)

t_maxs=(
	"0.07"
#	"0.13"
	"0.15"
#	"0.17"
)

bincs=(
	"1"
	"2"
	"3"
	"5"
	"10"
)

#----------------------------------------------------------------------------------------------------

#make -C .. "do_fit" || exit 1

for dataset in ${datasets[*]}
do
	for b_degree in ${b_degrees[*]}
	do
		for t_max in ${t_maxs[*]}
		do
			for binc in ${bincs[*]}
			do
				dir="fits_binc_${binc}/$dataset/exp$b_degree,t_max=$t_max"
				mkdir -p "$dir"

				echo "* $dir"

				extra_config=""
				SetStandardExtraConfig

				Ap="0"

				if [ "${t_max},${b_degree}" == "0.07,1" ]; then Ap="643.3"; fi
				if [ "${t_max},${b_degree}" == "0.07,2" ]; then Ap="646.2"; fi
				if [ "${t_max},${b_degree}" == "0.07,3" ]; then Ap="644.4"; fi

				if [ "${t_max},${b_degree}" == "0.15,1" ]; then Ap="635.2"; fi
				if [ "${t_max},${b_degree}" == "0.15,2" ]; then Ap="645.6"; fi
				if [ "${t_max},${b_degree}" == "0.15,3" ]; then Ap="648.9"; fi

				../do_fit -input "$dataset" -b-degree "$b_degree" -t-max "$t_max" -binc "$binc" $extra_config\
						-use-stat-unc 1 -use-syst-unc 1 -use-norm-unc 0\
						-reweight-low-t-points 1\
						-use-normalisation-from-a 1 -Ap-value "$Ap"\
						-output "$dir/fit.root" -results "$dir/fit.out" -tex "$dir/fit.tex" \
					&> "$dir/fit.log" &
			done
		done
	done
done
